### PR TITLE
rename: redisassert -> serverassert

### LINKED ISSUE #134: Rename `src/redisassert.c` to `src/serverassert.c`

### PR DESCRIPTION
**Pull request by 9bany**
fixes: https://github.com/valkey-io/valkey/issues/134

### CODE REVIEW

**Comment by zuiderkwast** [comment]
Hi @0del! Can you merge (or rebase) to lastest unstable? The spellcheck CI job has been fixed.

**Review by zuiderkwast — APPROVED** [review]
Looks good. Thanks for a small and simple PR. :)

There is a comment about "redisassert.h" inside serverassert.c. Do you want to fix it too? (If you don't, I can merge without that change too.)

**Comment by zuiderkwast** [comment]
I ignored the spellcheck problem, because I know it has been fixed on unstable so the build will pass after merging.

**Comment by 9bany** [comment]
i created a PR https://github.com/valkey-io/valkey/pull/142
please check ! @zuiderkwast

**Pull request merged**
