### PR TITLE
Adds new Placeholderkv logo to server logs.

### PR DESCRIPTION
**Pull request by roshkhatri**
```
./src/placeholderkv-server    
39910:C 27 Mar 2024 23:07:34.574 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
39910:C 27 Mar 2024 23:07:34.574 * oO0OoO0OoO0Oo Placeholderkv is starting oO0OoO0OoO0Oo
39910:C 27 Mar 2024 23:07:34.574 * Placeholderkv version=255.255.255, bits=64, commit=7734971c, modified=0, pid=39910, just started
39910:C 27 Mar 2024 23:07:34.574 # Warning: no config file specified, using the default config. In order to specify a config file use ./src/placeholderkv-server /path/to/redis.conf
39910:M 27 Mar 2024 23:07:34.575 * monotonic clock: POSIX clock_gettime


   (((((((((((((((((((((((////((((((((((((((((((((((((((((((((((((///(((((((((
   ((                                                                      ,((
   ((                                                  /(()))))            *((
   ((                                                 ()       )           *((
   ((                                                (/         #          *((
   ((                       ((((((                    (/       (           ,((
   ((                     (///(   ((                   (/(/))#             ,((
   ((                   (/////(#   ((                                      *((
   ((                 (////////(*   ((,                                    *((
   ((                (///////((      ((                                    ,((
   ((              (//////((/         ((            ((((((((               ,((
   ((             ((///////(           ((        ((///( (,  ((             ,((
   ((           ((///////((              ((     ((/////(     ((            *((
   ((          (////////((                ((  ((////////((    ((           *((
   ((         (//////((/                     (////////((       ((           ((
   ((       (///////((                      (/////////((        ((         ,((
   ((      (///////((                      (///////////(         ((        *((
   ((    (///////((                      (////////////(           ((       *((
   ((   (///////((                      ((///////////((            ((      ,((
   ((  (///////((                     (///////////(((               ((     ,((
   ((#////////((                     (/////////(((                   ((     ((
   (((((((((((/(((((((((((((((((((((((((((((((((((((((//(((((((((/((((((((((((
                                                                              
                                                                              
                       Placeholderkv 255.255.255 (7734971c/0) 64 bit                        
                                                                              
                         Running in standalone mode
                         Port: 6379
                         PID: 39910
                                                                              
                                                                              
                        (Website will be here soon)                           
                                                                              
                                                                              
                                                                              

39910:M 27 Mar 2024 23:07:34.576 * Server initialized
39910:M 27 Mar 2024 23:07:34.576 * Loading RDB produced by version 255.255.255
39910:M 27 Mar 2024 23:07:34.576 * RDB age 1425 seconds
39910:M 27 Mar 2024 23:07:34.576 * RDB memory usage when created 0.83 Mb
39910:M 27 Mar 2024 23:07:34.576 * Done loading RDB, keys loaded: 0, keys expired: 0.
39910:M 27 Mar 2024 23:07:34.576 * DB loaded from disk: 0.000 seconds
39910:M 27 Mar 2024 23:07:34.576 * Ready to accept connections tcp
^C39910:signal-handler (1711580863) Received SIGINT scheduling shutdown...
39910:M 27 Mar 2024 23:07:43.696 * User requested shutdown...
39910:M 27 Mar 2024 23:07:43.696 * Saving the final RDB snapshot before exiting.
39910:M 27 Mar 2024 23:07:43.700 * DB saved on disk
39910:M 27 Mar 2024 23:07:43.700 # Placeholderkv is now ready to exit, bye bye...
```

### CODE REVIEW

**Review by hpatro — APPROVED** [review]
We should consider sticking with PlaceholderKV 🚀

**Comment by roshkhatri** [comment]
```
./src/placeholderkv-server    
39910:C 27 Mar 2024 23:07:34.574 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
39910:C 27 Mar 2024 23:07:34.574 * oO0OoO0OoO0Oo Placeholderkv is starting oO0OoO0OoO0Oo
39910:C 27 Mar 2024 23:07:34.574 * Placeholderkv version=255.255.255, bits=64, commit=7734971c, modified=0, pid=39910, just started
39910:C 27 Mar 2024 23:07:34.574 # Warning: no config file specified, using the default config. In order to specify a config file use ./src/placeholderkv-server /path/to/redis.conf
39910:M 27 Mar 2024 23:07:34.575 * monotonic clock: POSIX clock_gettime


   (((((((((((((((((((((((////((((((((((((((((((((((((((((((((((((///(((((((((
   ((                                                                      ,((
   ((                                                  /(()))))            *((
   ((                                                 ()       )           *((
   ((                                                (/         #          *((
   ((                       ((((((                    (/       (           ,((
   ((                     (///(   ((                   (/(/))#             ,((
   ((                   (/////(#   ((                                      *((
   ((                 (////////(*   ((,                                    *((
   ((                (///////((      ((                                    ,((
   ((              (//////((/         ((            ((((((((               ,((
   ((             ((///////(           ((        ((///( (,  ((             ,((
   ((           ((///////((              ((     ((/////(     ((            *((
   ((          (////////((                ((  ((////////((    ((           *((
   ((         (//////((/                     (////////((       ((           ((
   ((       (///////((                      (/////////((        ((         ,((
   ((      (///////((                      (///////////(         ((        *((
   ((    (///////((                      (////////////(           ((       *((
   ((   (///////((                      ((///////////((            ((      ,((
   ((  (///////((                     (///////////(((               ((     ,((
   ((#////////((                     (/////////(((                   ((     ((
   (((((((((((/(((((((((((((((((((((((((((((((((((((((//(((((((((/((((((((((((
                                                                              
                                                                              
                       Placeholderkv 255.255.255 (7734971c/0) 64 bit                        
                                                                              
                         Running in standalone mode
                         Port: 6379
                         PID: 39910
                                                                              
                                                                              
                        (Website will be here soon)                           
                                                                              
                                                                              
                                                                              

39910:M 27 Mar 2024 23:07:34.576 * Server initialized
39910:M 27 Mar 2024 23:07:34.576 * Loading RDB produced by version 255.255.255
39910:M 27 Mar 2024 23:07:34.576 * RDB age 1425 seconds
39910:M 27 Mar 2024 23:07:34.576 * RDB memory usage when created 0.83 Mb
39910:M 27 Mar 2024 23:07:34.576 * Done loading RDB, keys loaded: 0, keys expired: 0.
39910:M 27 Mar 2024 23:07:34.576 * DB loaded from disk: 0.000 seconds
39910:M 27 Mar 2024 23:07:34.576 * Ready to accept connections tcp
^C39910:signal-handler (1711580863) Received SIGINT scheduling shutdown...
39910:M 27 Mar 2024 23:07:43.696 * User requested shutdown...
39910:M 27 Mar 2024 23:07:43.696 * Saving the final RDB snapshot before exiting.
39910:M 27 Mar 2024 23:07:43.700 * DB saved on disk
39910:M 27 Mar 2024 23:07:43.700 # Placeholderkv is now ready to exit, bye bye...
```

**Comment by hwware** [comment]
Is it a mountain?

**Comment by hpatro** [comment]
> Is it a mountain?

It's a logo for Placeholder 😂. We also had put it up in Discord. 

@roshkhatri now that we have finalised a name, we should skip this change and wait for someone to come up with a creative logo.

**Comment by roshkhatri** [comment]
Yes we'll wait for that and update it later😂

**Comment by roshkhatri** [comment]
Addressed in https://github.com/valkey-io/valkey/pull/77

**Pull request closed without merging**
