### PR TITLE
Update debug.c

### PR DESCRIPTION
**Pull request by eltociear**
minor fix

### CODE REVIEW

**Review by madolson — APPROVED** [review]
Thanks for **the** fix.

**Comment by madolson** [comment]
Btw, we ask to sign a DCO (https://github.com/valkey-io/valkey/pull/93/checks?check_run_id=23256701353 for how to fix it). This isn't a CLA, it's just a commitment that you own the right to push the change.

**Comment by hwware** [comment]
@eltociear Could you please sign the DCO ? Thanks

**Comment by madolson** [comment]
@eltociear DCO still isn't signed correctly.

**Pull request closed without merging**
