### PR TITLE
Rename redis.conf to valkey.conf, with replace word redis to valkey, remaining'redis' is needed

### PR DESCRIPTION
**Pull request by LiiNen**
Related to issue https://github.com/valkey-io/valkey/issues/135, PR https://github.com/valkey-io/valkey/pull/109

I have seen the file redis.conf, and realized that it **cannot be solved by just fixing string** "redis to valkey" and "Redis to Valkey", and seems like there are some PRs - just replacing this string.
So, I take a look one by one. These are the results.

### Basically, I followed the rule below:
```
Fix: "Redis -> Valkey" string 'Redis' in description
Fix: "redis -> valkey" string 'redis' in examples like 'redis.conf' (for filename or else)
```

### And these are exception for above rule
```
# line 62, 1362, 2148, 2305, 2317
Fix: "redis -> Valkey", string 'redis' in description - maybe these were typos

# line 836, 1014, 1391, 1776, 1879
Remain: I think we do not have own web site for now.

# line 1448
Remain: post by antirez: static web site
```
**Note:** I think these remains are needed to be managed by a new issue, and to be fixed when web site of valkey is fully ready :)

### Lastly, these are something that needed to be reviewed, I think
```
# line 176
Add: 'Valkey also follows this default'.
```
There are version histories also in other spaces, but I didn't add it to them intentionally. If you like it, I'll also add it to them. Or just leaving them will be fine too.

```
# line 543~
Add: Valkey version or greater
# line 1397
Fix and Add: Valkey version 'or greater': make same format as line 543.
```
Added more, not harmful for previous redis users.
I have fixed 'and newer' to 'or greater'. Is it fine?

#### really lastly, filename has been renamed

Thanks,

p.s. I didn't mean to steal others' contribution. I'll be glad if these changes (with my intention, effort, and report for suggestion) to be merged in main branch, in any way, from anyone, for Valkey :)

### CODE REVIEW

**Comment by LiiNen** [comment]
Maybe I misunderstand issue #135.
The new PR https://github.com/valkey-io/valkey/pull/145 actually fix it, though this isn't containing my changes.
We were focusing to each other things:
changing from **'redis.conf' to 'valkey.conf' that refer it**, and changing from **'redis' to 'valkey' in config file**.

**Comment by 9bany** [comment]
@LiiNen Sorry ab that, i did not see your PR after i created this https://github.com/valkey-io/valkey/pull/145

**Comment by LiiNen** [comment]
@0del Nope, I have seen your PR, and found that we are focusing to totally different things.
Maybe you are targeting the exact issue, and I was targeting it, just fixing words in conf file with narrow view lol.
Seems like we worked in different side, so it won't be any issues maybe, just I thought

Thanks for your comment :)

**Comment by zuiderkwast** [comment]
Also note #29. We have a little chaos here. :grin:

**Comment by zuiderkwast** [comment]
Can you assign yourselves to issues? If not, just write in a comment on the issue, so that others can avoid doing the same work. We can also split issues into smaller issues if some of them are too big. Just ping me.

**Comment by LiiNen** [comment]
@zuiderkwast  Thanks, and sorry for missing that PR.

Actually, it really jumps into chaos 😅 
There are too many PRs that contains changes for lots of files, and sadly some of them are missing because it is huge actually.
Maybe some notice or assigning to users to fix it with smaller issues will be better to solve this chaos.

BTW, I am sure can be assignee, but I'm not sure about your actual intention. @0del can also be a nice assignee.
Or else, could you split it into more smaller issues and assign @0del and me to each of those? This would be nice, cause we are working at different side of view, and both is worth.

**Comment by zuiderkwast** [comment]
Obsolete, right?

**Pull request closed without merging**
