### PR TITLE
[New] Migrate zmalloc.c unit tests to new test framework.

### PR DESCRIPTION
**Pull request by karthyuom**
This is the actual PR which is created to migrate all tests related to zmalloc into new test framework as part of the parent issue https://github.com/valkey-io/valkey/issues/428.

Due to the conflict issue, the other PR https://github.com/valkey-io/valkey/pull/459 will be closed.

@madolson please review this and merge, as this accommodates all the intended changes.

### CODE REVIEW

**Review by madolson — APPROVED** [review]

**Comment by madolson** [comment]
@karthyuom Would you mind taking a look at this daily run, https://github.com/valkey-io/valkey/actions/runs/9104302437/job/25027896513 and https://github.com/valkey-io/valkey/actions/runs/9104302437/job/25027896060. For some reason the address sanitizer variants are not happy about this test, but the normal CI is.

**Comment by karthyuom** [comment]
@madolson  I couldn't reproduce the above in my local test environment with the following command:

`make all-with-unit-tests OPT=-O3 SANITIZER=address SERVER_CFLAGS='-DSERVER_TEST -Werror -DDEBUG_ASSERTIONS'`

Also, the error `unit/../zmalloc.h:122:47: error: unknown type name 'size_t'` , I am not sure why we didn't have this problem before with the legacy test, even though I didn't change anything in the _zmalloc.h_.

Anyway, I will try to dive deeper to see where the problem is.

**Comment by madolson** [comment]
https://github.com/valkey-io/valkey/pull/516 Should fix it. I was only able to reproduce it running on ubuntu 22 with ASAN, it didn't error out on either of my mac development machines.

**Comment by karthyuom** [comment]
> #516 Should fix it. I was only able to reproduce it running on ubuntu 22 with ASAN, it didn't error out on either of my mac development machines.

That is interesting. I tried the same fix with the help of daily CI in my forked repo, but still complaint about `size_t` (see https://github.com/karthyuom/valkey/actions/runs/9132472124/job/25113889640).

I just saw similar error even in the valkey's recent daily CI run: https://github.com/valkey-io/valkey/actions/runs/9183451888/job/25254186187. Looks like the issue is still not fixed(?)

**Comment by madolson** [comment]
So, https://github.com/valkey-io/valkey/actions/runs/9183451888 was executed by me on a different commit that was missing the commit. 

https://github.com/valkey-io/valkey/actions/runs/9183169208 is the latest daily from unstable and it looks green.

**Pull request merged**
