### PR TITLE
Integrate the bugfixes of Redis 7.2.5

### LINKED ISSUE #561: Integrate the bugfixes of Redis 7.2.5
Redis 7.2.5 has been published: https://github.com/redis/redis/releases/tag/7.2.5

This release uses the "old" Redis license.

Please integrate the bugfixes of this release into Valkey.

### PR DESCRIPTION
**Pull request by PingXie**

### CODE REVIEW

**Comment by enjoy-binbin** [comment]
odd, i see in https://github.com/valkey-io/valkey/commits/7.2/ we still have the commit https://github.com/valkey-io/valkey/commit/8b7db306fd0169077e9d335e0eaa59cfa0b6d085, do we need we do a `git reset --hard 8c2a76f5846821b4d2ad5e5a0b9f39e01f381c82` in 7.2 branch? and drop the commit we squashed last time?

**Comment by PingXie** [comment]
> odd, i see in https://github.com/valkey-io/valkey/commits/7.2/ we still have the commit [8b7db30](https://github.com/valkey-io/valkey/commit/8b7db306fd0169077e9d335e0eaa59cfa0b6d085), do we need we do a `git reset --hard 8c2a76f5846821b4d2ad5e5a0b9f39e01f381c82` in 7.2 branch? and drop the commit we squashed last time?

Hmm, I think so. Let give it a try

**Comment by PingXie** [comment]
> > odd, i see in https://github.com/valkey-io/valkey/commits/7.2/ we still have the commit [8b7db30](https://github.com/valkey-io/valkey/commit/8b7db306fd0169077e9d335e0eaa59cfa0b6d085), do we need we do a `git reset --hard 8c2a76f5846821b4d2ad5e5a0b9f39e01f381c82` in 7.2 branch? and drop the commit we squashed last time?
> 
> Hmm, I think so. Let give it a try

Ok, I have hard-reset 7.2 to remove commit [8b7db30]. I think we are good to go

**Comment by PingXie** [comment]
btw, I think we should remove centos7 from the daily test pass. I am not sure about the freebsd hang though. The VM can't start for more than 4 hours? Have you seen this?

**Review by enjoy-binbin — APPROVED** [review]
yean, i think now we are good to go.

> btw, I think we should remove centos7 from the daily test pass. I am not sure about the freebsd hang though. The VM can't start for more than 4 hours? Have you seen this?

yes, look like we should remove the centos7 part. The freebsd is a known issue (i don't know how to fix) so i think we can skip it for now.

**Pull request merged**
