### PR TITLE
Fix the typo in the valkey.conf

### PR DESCRIPTION
**Pull request by Shivshankar-Reddy**

### CODE REVIEW

**Review by enjoy-binbin — COMMENTED** [review]
This doesn't look like typo, it's written this way on purpose i guess

**Comment by Shivshankar-Reddy** [comment]
Hi @enjoy-binbin ,
Thank you for the review!
Do you mean they want to emphasize something? or does it have any acronym?

**Review by zuiderkwast — APPROVED** [review]
I don't know why BE was capitalized.

Mistake? Maybe.

Acronym? I don't think so.

Emphasis? Maybe, but why emphasis this word? Very strange.

We can change to "be".

**Comment by enjoy-binbin** [comment]
> Emphasis? Maybe, but why emphasis this word? Very strange.

i guess it is just a habit from oran. Something like a modal word. Ok, i am good with merging it.

**Pull request merged**
