### PR TITLE
Allow CLUSTER NODES/INFO/MYID/MYSHARDID during loading state

### PR DESCRIPTION
**Pull request by hpatro**
Allow CLUSTER subcommands NODES, INFO, MYID, MYSHARDID while loading data.

It's safe to allow them and it's helpful for clients to get cluster nodes/info information
during a node failover and while loading data to monitor the
state of the cluster.

### CODE REVIEW

**Review by madolson — APPROVED** [review]

**Comment by madolson** [comment]
I'm not sure if this is really a major decision, but can get folks input. @valkey-io/core-team Please vote if this seems reasonable. The `CLUSTER` commands were originally marked as no-loading because of the failover commands, but the remaining commands should be safe to execute. We already allow `CLUSTER SLOTS` and `CLUSTER SHARDS`.

**Review by zuiderkwast — APPROVED** [review]

**Review by enjoy-binbin — APPROVED** [review]
do we also want to allow cluster myid?

**Comment by hpatro** [comment]
> do we also want to allow cluster myid? 

Haven't heard of use case for it, but seems safe to enable it during loading.
So, `CLUSTER MYID` and `CLUSTER MYSHARDID` ?

**Review by enjoy-binbin — APPROVED** [review]
LGTM.

**Review by soloestoy — APPROVED** [review]

**Pull request merged**
