### PR TITLE
Add timestamp to log messages in test_helper.tcl

### PR DESCRIPTION
**Pull request by PingXie**
- Introduced `current_time` function to generate a formatted timestamp.
- Updated log messages in `read_from_test_client` to include timestamps.

This change aims to help analyze the recent slew of test timeout issues by providing precise timing information in the logs, allowing for better tracking and debugging of test execution times.

https://github.com/hwware/valkey/actions/runs/9715726013/job/26817778389#step:6:3736

### CODE REVIEW

**Comment by madolson** [comment]
Github has timestamps:

image

I actually don't like this change because I have my own way of adding in a timestamp when running tests. I would at the very least like to have an optional to enable it.

**Comment by PingXie** [comment]
Nice!

How do you add timestamps locally? I can make this optional as I'd like to have timestamps locally too but if there is already a way that doesn't require code change that would be even better.

**Review by enjoy-binbin — COMMENTED** [review]
i think it is a good idea to add this, i've had this thought in the past. Do you have a screenshot of the example output?

**Comment by madolson** [comment]
> How do you add timestamps locally? I can make this optional as I'd like to have timestamps locally too but if there is already a way that doesn't require code change that would be even better.

Typically I use `ts` which is available in moreutils (which is available on mac and practically all linux distros), and gives an output like:

```
madolson@MacBook-Air-5 valkey % ./runtest |ts
Jun 30 22:02:19 Cleanup: may take some time... OK
Jun 30 22:02:19 Starting test server at port 21079
Jun 30 22:02:19 [ready]: 12546
Jun 30 22:02:19 Testing unit/pubsub
```

**Comment by madolson** [comment]
> i think it is a good idea to add this, i've had this thought in the past. Do you have a screenshot of the example output?

You can check the CI link, https://github.com/valkey-io/valkey/actions/runs/9721454412/job/26834153304?pr=714.

**Comment by PingXie** [comment]
I think `ts` is great. There is no need for this PR then. Less is more :-)

**Pull request closed without merging**
