### PR TITLE
Rename remaining test procedures missed in `#287`

### PR DESCRIPTION
**Pull request by Shivshankar-Reddy**
Renamed below procedures and variables as follows.

redis_cluster             ->     valkey_cluster
redis1                    ->     valkey1
redis2                    ->     valkey2
get_redis_dir             ->     get_valkey_dir
test_redis_cli_rdb_dump   ->     test_valkey_cli_rdb_dump
test_redis_cli_repl       ->     test_valkey_cli_repl
redis-cli                 ->     valkey-cli
redis_reset_state         ->     valkey_reset_state
redisHandle               ->     valkeyHandle
redis_safe_read           ->     valkey_safe_read
redis_safe_gets           ->     valkey_safe_gets
redis_write               ->     valkey_write
redis_read_reply          ->     valkey_read_reply
redis_readable            ->     valkey_readable
redis_readnl              ->     valkey_readnl
redis_writenl             ->     valkey_writenl
redis_read_map            ->     valkey_read_map
redis_read_line           ->     valkey_read_line
redis_read_null           ->     valkey_read_null
redis_read_bool           ->     valkey_read_bool
redis_read_double         ->     valkey_read_double
redis_read_verbatim_str   ->     valkey_read_verbatim_str
redis_call_callback       ->     valkey_call_callback

### CODE REVIEW

**Review by enjoy-binbin — APPROVED** [review]
full CI: https://github.com/valkey-io/valkey/actions/runs/8813920744

**Review by zuiderkwast — APPROVED** [review]
Very good!

**Comment by zuiderkwast** [comment]
And very good PR description!

**Comment by Shivshankar-Reddy** [comment]
> full CI: https://github.com/valkey-io/valkey/actions/runs/8813920744

I re-run the workflow and now all the test passed. Thanks!

**Pull request merged**
