### PR TITLE
Rename Redis to Valkey in the crash report.

### PR DESCRIPTION
**Pull request by zhulipeng**
This patch try to correct the server crash report.
Rename Redis to Valkey.

### CODE REVIEW

**Review by madolson — APPROVED** [review]
I totally forgot about this, this is another thing to backport.

**Review by enjoy-binbin — APPROVED** [review]

**Comment by zhulipeng** [comment]
Resolved in https://github.com/valkey-io/valkey/pull/263.

**Comment by madolson** [comment]
@lipzhu I would keep this open. We may still want to apply the changed on `REDIS BUG REPORT END. Make sure to include from START to END` that this PR implements.

**Comment by zhulipeng** [comment]
> @lipzhu I would keep this open. We may still want to apply the changed on `REDIS BUG REPORT END. Make sure to include from START to END` that this PR implements.

Ok, reopen the PR and solve the conflicts.

**Comment by madolson** [comment]
Thanks, we need to decide if this is a breaking change, putting it in the 8.0 project for the time being.

**Comment by zuiderkwast** [comment]
This is a potential candidate for configurable redis compat mode. #274

**Comment by zhulipeng** [comment]
Solved in https://github.com/valkey-io/valkey/pull/306.

**Pull request closed without merging**
