### PR TITLE
8.0 GA Release

### PR DESCRIPTION
**Pull request by PingXie**

### CODE REVIEW

**Review by enjoy-binbin — APPROVED** [review]

**Comment by PingXie** [comment]
@valkey-io/core-team PTAL

**Comment by enjoy-binbin** [comment]
[Make KEYS to be an exact match if there is no pattern](https://github.com/valkey-io/valkey/pull/1031/commits/3bcd6735f40b3fdd1cc37bb667a8f2428ff5e9e6)
[Revert make KEYS to be an exact match if there is no pattern](https://github.com/valkey-io/valkey/pull/1031/commits/d8a305c33302b58634e576972a042a5327f86518)
[Fix reconfiguring sub-replica causing data loss when myself change shard_id](https://github.com/valkey-io/valkey/pull/1031/commits/e458f9cd268826e85e749ae593fba233c7c25edd)

these there (the top 3) is dup, these was merged when RC2

and this one is missing i guess https://github.com/valkey-io/valkey/pull/981

**Comment by enjoy-binbin** [comment]
https://github.com/valkey-io/valkey/pull/981
https://github.com/valkey-io/valkey/pull/1025

these two are missing, other LGTM.

**Comment by PingXie** [comment]
all fixed.

#981 was not missing but it was lumped with another PR #1027 for some reason. I have rebased/fixed this commit.

**Comment by zuiderkwast** [comment]
This PR appears to have thousands of lines changed. Is it rebased onto current latest 8.0 branch or how is it done?

What's the difference between this PR and #1030? It has much fewer changed lines.

Release notes update for GA?

**Comment by PingXie** [comment]
> This PR appears to have thousands of lines changed. Is it rebased onto current latest 8.0 branch or how is it done?
> 
> What's the difference between this PR and #1030? It has much fewer changed lines.


#1030 is everything we marked "to be backported" in the 8.0 project and this is everything "unstable". We need to make a call between 1030 and 1031 (this one) but we don't need both. I am leaning towards going with 1031.

> 
> Release notes update for GA?

The release notes will have to come after us deciding which pr to take.

**Comment by PingXie** [comment]
> #981 #1025
> 
> these two are missing, other LGTM.

btw, #1025 got lumped into the commit for #981. I don't think it is easier to split at this point so I am going to leave it as-is (@hwware any concerns?). 

Plus, with us taking everything in unstable, my understanding is that we prefer a squash merge so all that matters is the payload. thoughts?

**Comment by zuiderkwast** [comment]
> Plus, with us taking everything in unstable, my understanding is that we prefer a squash merge so all that matters is the payload. thoughts?

You think nobody will use `git log` on the 8.0.0 tag or branch? I think it'd be good to include all commits. When we squash-backported to 7.2 we decided to revert that and take separate commits instead.

Another idea: We could start off a new 8.0 branch from unstable and just add the release notes on top. Would that work?

**Review by zuiderkwast — APPROVED** [review]

**Comment by PingXie** [comment]
>You think nobody will use git log on the 8.0.0 tag or branch? I think it'd be good to include all commits. When we squash-backported to 7.2 we decided to revert that and take separate commits instead.

Yeah, sure will keep all the commits.

>Another idea: We could start off a new 8.0 branch from unstable and just add the release notes on top. Would that work?

Will it look odd in the commit history if the GA release isn't a descendant of the RC releases?

**Pull request merged**
