### PR TITLE
updated modules examples to reference Valkey*

### PR DESCRIPTION
**Pull request by dmitrypol**
we already have valkeymodule.h with new naming convention and reference it from modules examples

### CODE REVIEW

**Comment by madolson** [comment]
Thanks @dmitrypol 

We require a DCO, see https://github.com/valkey-io/valkey/blob/unstable/CONTRIBUTING.md#developer-certificate-of-origin.

**Comment by madolson** [comment]
You can fix this by doing:
```
git rebase HEAD~1 --signoff
git push --force origin <name of your branch>
```

**Review by zuiderkwast — APPROVED** [review]
LGTM

Are these built by the CI jobs? It'd be good to at least see that they compile. (Even better would be to have tests for them to check that thwy actually work, but that's a different job. We could add a README for these examples too some other time.)

**Comment by madolson** [comment]
> Are these built by the CI jobs? It'd be good to at least see that they compile. (Even better would be to have tests for them to check that thwy actually work, but that's a different job. We could add a README for these examples too some other time.)

These are just references as far as I understand. I think in the fullness of time we might want to move them elsewhere (including maybe compiling and testing them).

One alternative is we could also delete them, and transfer all the functions they call into the modules we build for tests.

**Comment by zuiderkwast** [comment]
Ok, we can postpone what to do with them, but I think we shall merge this rebranding for now.

@dmitrypol have you tried to compile them? (Run make in that directory.)

**Comment by dmitrypol** [comment]
@zuiderkwast - yes, I have compiled all example modules, loaded them into valkey-server and manually tested the commands

**Pull request merged**
