### PR TITLE
refactore: Move test to seprate module to can be run separetly

### LINKED ISSUE #428: Migrate unit tests to new framework
The legacy unit tests were a collection of distinct tests stored at the bottom of various files, that required rebuilding the server with a special flag and starting the server. We're moving to a new [framework](https://github.com/valkey-io/valkey/pull/344) that can always be built and are running on a unified infrastructure. This issue is keeping track of migration from the old to new framework.

To migrate the tests, remove the custom testing code in the testing file lists listed below, create a new test like src/unit/test_*.c, and remove the reference in https://github.com/valkey-io/valkey/blob/5b1fd222ed97430dfeef27a95aeb7e1fb8fd1352/src/server.c#L6890. See the [README](https://github.com/valkey-io/valkey/blob/unstable/src/unit/README.md) for more information about writing a new unit test. 

- [x] : [Zipmap.c](https://github.com/valkey-io/valkey/blob/5b1fd222ed97430dfeef27a95aeb7e1fb8fd1352/src/zipmap.c#L444) https://github.com/valkey-io/valkey/pull/474
- [X] : [util.c](https://github.com/valkey-io/valkey/blob/5b1fd222ed97430dfeef27a95aeb7e1fb8fd1352/src/util.c#L1378) https://github.com/valkey-io/valkey/pull/448
- [x] : [kvstore.c](https://github.com/valkey-io/valkey/blob/5b1fd222ed97430dfeef27a95aeb7e1fb8fd1352/src/kvstore.c#L869) https://github.com/valkey-io/valkey/pull/446
- [x] : [dict.c](https://github.com/valkey-io/valkey/blob/5b1fd222ed97430dfeef27a95aeb7e1fb8fd1352/src/dict.c#L1758)https://github.com/valkey-io/valkey/pull/673 and https://github.com/valkey-io/valkey/pull/946
- [X] : [endianconv.c](https://github.com/valkey-io/valkey/blob/5b1fd222ed97430dfeef27a95aeb7e1fb8fd1352/src/endianconv.c#L104) https://github.com/valkey-io/valkey/pull/458
- [x] : [quicklist.c](https://github.com/valkey-io/valkey/blob/5b1fd222ed97430dfeef27a95aeb7e1fb8fd1352/src/quicklist.c#L215) https://github.com/valkey-io/valkey/pull/515
- [X] : [sds.c](https://github.com/valkey-io/valkey/blob/5b1fd222ed97430dfeef27a95aeb7e1fb8fd1352/src/sds.c#L1232) https://github.com/valkey-io/valkey/pull/478
- [x] : [sha1.c](https://github.com/valkey-io/valkey/blob/5b1fd222ed97430dfeef27a95aeb7e1fb8fd1352/src/sha1.c#L211) (https://github.com/valkey-io/valkey/pull/470)
- [x] : [ziplist.c](https://github.com/valkey-io/valkey/blob/5b1fd222ed97430dfeef27a95aeb7e1fb8fd1352/src/ziplist.c#L1689) https://github.com/valkey-io/valkey/pull/486
- [x] : [zmalloc.c](https://github.com/valkey-io/valkey/blob/5b1fd222ed97430dfeef27a95aeb7e1fb8fd1352/src/zmalloc.c#L911) https://github.com/valkey-io/valkey/pull/493
- [x] : [listpack.c](https://github.com/valkey-io/valkey/blob/5b1fd222ed97430dfeef27a95aeb7e1fb8fd1352/src/listpack.c#L1682) (https://github.com/valkey-io/valkey/pull/484) and #949
- [x] : Cleanup remaining references of SERVER_TEST (#515)

### PR DESCRIPTION
**Pull request by aliraad79**
Hi, I think this will help with #428 merge request.
This is my first merge request on this repo and any comment is helpful for me. 
Thank you in advance. 
Fix #428

### CODE REVIEW

**Comment by madolson** [comment]
Thanks for helping, it looks like some of the tests are failing. Did you run:
```
make valkey-unit-tests
./src/valkey-unit-tests 
```

To make sure they all run?

**Comment by aliraad79** [comment]
No i don't do that. I fix the tests and push it again.

**Comment by aliraad79** [comment]
Hi. I fix some problems but there is some bigger problems.
for test_dict for example we want to use dict_force_resize_ratio variable but it is declared in .c file and not in header. What should i do? can i move this thing to header or there is a trick to include this type of thing only in test?
another problem is that some functions and # defines are also in .c file.

**Comment by madolson** [comment]
> for test_dict for example we want to use dict_force_resize_ratio variable but it is declared in .c file and not in header. What should i do? can i move this thing to header or there is a trick to include this type of thing only in test?
another problem is that some functions and # defines are also in .c file.

For other tests like listpack we've just been including the .c file. Since some other folks have already ported some of the other tests, do you mind just re-submitting the PR just for the dict.c test case? It's a bit easier to merge as well.

**Comment by madolson** [comment]
Looks like a lot of this work got split up and handled in other PRs, so going to close this.

**Pull request closed without merging**
