### PR TITLE
Updated modules examples and tests to use valkey vs redis

### PR DESCRIPTION
**Pull request by dmitrypol**
Scope of the changes:
- updated example modules to reference Valkey vs Redis in variable names
- updated tests to use valkeymodule.h
- updated vars in tests/modules to use valkey vs redis in variable names

Summary of the testing:
- ran make for all modules, loaded them into valkey-server and tested commands
- ran make for test/modules
- ran make test for the entire codebase

### CODE REVIEW

**Review by zuiderkwast — APPROVED** [review]
Great.

The exact replacements, is it just

    REDISMODULE -> VALKEYMODULE
    RedisModule -> ValkeyModule
    redismodule -> valkeymodule

Nothing else manually edited?

Regarding running module tests, it's done with `make test-modules` or `./runtest-moduleapi`.

**Comment by zuiderkwast** [comment]
I see that the CI test run the module API tests, so I think it's safe to merge. Thanks!

**Comment by dmitrypol** [comment]
@zuiderkwast  - correct, lots of search/replace/test carefully.

**Comment by madolson** [comment]
Just want to post that we no longer have a test validating that the old (RedisModule_*) modules can still be loaded. We should probably add one. @dmitrypol Do you think you can help with that?

**Comment by dmitrypol** [comment]
@madolson - I saw this in logs when I loaded Rust module.  I presume this is related?  We want to support RedisModules for a while in the sprit of continuity.  

`50905:M 23 Apr 2024 10:19:30.434 * Legacy Redis Module .../redismodule-rs/target/debug/examples/libdmitry2.dylib found`

**Comment by madolson** [comment]
Yes, that is related. That is the specific log line that get's printed when a legacy Redis module is loaded.

**Comment by zuiderkwast** [comment]
Can we have a test case that does `sed s/valkey/redis/g;s/Valkey/Redis/g;s/VALKEY/REDIS/g` on the modules and the test cases and then tries to compile and run them? Simple hack

**Pull request merged**
