### PR TITLE
Use hashtable as the default type of temp set object during sunion/sdiff.

### PR DESCRIPTION
**Pull request by zhulipeng**
## Issue Description 
According to existing code logic, when did operation like `sunion` and `sdiff` , the temp set object could be `intset`, `listpack` and `hashtable`,  for the `listpack`, the efficiency is low when did operation like `find` and `compare` , need to traverse all elements. When we exploring the hotspots, found the `lpFind` and `memcmp` has been the bottleneck when running workloads like below:

- [memtier_benchmark-2keys-set-10-100-elements-sunion.yml](https://github.com/redis/redis-benchmarks-specification/blob/main/redis_benchmarks_specification/test-suites/memtier_benchmark-2keys-set-10-100-elements-sunion.yml)   
- [memtier_benchmark-2keys-set-10-100-elements-sdiff.yml](https://github.com/redis/redis-benchmarks-specification/blob/main/redis_benchmarks_specification/test-suites/memtier_benchmark-2keys-set-10-100-elements-sdiff.yml)

image

## Optimization 

This patch try to set the temp set object as default hash table type. And did a simple predication of the temp set object encoding when initialize `dstset` to reduce the unnecessary conversation. 

### Test Environment

- OPERATING SYSTEM: Ubuntu 22.04.4 LTS
- Kernel: 5.15.0-116-generic
- PROCESSOR: Intel Xeon Platinum 8380
- Server and Client in same socket.

#### Server Configuration
```
taskset -c 0-3 ~/valkey/src/valkey-server /tmp/valkey.conf

port 9001
bind * -::*
daemonize no
protected-mode no
save ""
```

#### Performance Boost 

| Test Name| Perf Boost|
|-|-|
|[memtier_benchmark-2keys-set-10-100-elements-sunion.yml](https://github.com/redis/redis-benchmarks-specification/blob/main/redis_benchmarks_specification/test-suites/memtier_benchmark-2keys-set-10-100-elements-sunion.yml)   |41%|
|[memtier_benchmark-2keys-set-10-100-elements-sdiff.yml](https://github.com/redis/redis-benchmarks-specification/blob/main/redis_benchmarks_specification/test-suites/memtier_benchmark-2keys-set-10-100-elements-sdiff.yml) |27%|

### More Tests
With above test set which have total 110 elements in the 2 given sets. We also did some benchmarking by adjusting the total number of elements in all given sets. We can still observe the performance boost.

image

### CODE REVIEW

**Review by hpatro — COMMENTED** [review]
It's about tradeoff between CPU vs memory, right? Could we capture the temporal memory utilization with both the approaches.

**Comment by zhulipeng** [comment]
@hpatro Thanks for your comments :).

> It's about tradeoff between CPU vs memory, right? 

It's not about tradeoff of CPU and memory, the CPU utilization of the benchmark are both 100% for both 2 approaches.
I think it is about the data structure optimization. We can make the time complexity of temp set object `find`  from O(n) to O(1).

**Before (Listpack):** 
**Description:** Traverse all elements in listpack and `memcmp`.
**Time complexity: O(n)**
**After (Hashtable):**
**Description:** Hash element and get bucket index, if index is null then insert otherwise do `memcmp`.
**Time complexity: O(1)**

>Could we capture the temporal memory utilization with both the approaches.

I used `sar -r 1 60` to compare the gap between the 2 approaches. The metrics `%memused` increased **~0.01%** (Total memory is 256G) during the benchmark of [memtier_benchmark-2keys-set-10-100-elements-sunion.yml](https://github.com/redis/redis-benchmarks-specification/blob/main/redis_benchmarks_specification/test-suites/memtier_benchmark-2keys-set-10-100-elements-sunion.yml). 
Another reference is the metrics `used_memory_peak` increase from `4603096` to `4619496`, increase **~0.35%**.

Considering that the perf boost and temp memory will be released soon. I think it is worth.

**Comment by hpatro** [comment]
@lipzhu I thought the decision of choosing `intset` as the default encoding type for the interim operation was made to have a very low memory footprint and move to `listpack`/`ht` if required. 

Thanks for sharing the details, I also think it makes sense to use `ht` by default for interim objects.

**Comment by zuiderkwast** [comment]
Thanks @lipzhu!

This is a good idea, at least for SUNION and SDIFF. The set we're creating is temporary.

But sunionDiffGenericCommand is also used for SUNIONSTORE and SDIFFSTORE (called with `dstkey != NULL`). For the STORE commands, the object is not temporary. It is stored in a key afterwards. In this case, we may want to store a compact representation, so here I agree with @hpatro's comment.

> I thought the decision of choosing `intset` as the default encoding type for the interim operation was made to have a very low memory footprint and move to `listpack`/`ht` if required.

I can see three options:

1. Initialize as HT only if dstset == NULL and intset otherwise
2. Initialize as HT but for the store commands (dst != NULL) try to convert to listpack or intset afterwards. Currently, we only convert to "larger" encodings, i.e. we never convert from HT to listpack, for example.
3. Just accept that SUNIONSTORE and SINTERSTORE always stores HT encoded sets (current PR implementation).

At the minimum, we can do 1. I don't know if 2 is complex or if 3 is risky about using too much memory. WDYT?

**Comment by zhulipeng** [comment]
> Thanks @lipzhu!
> 
> This is a good idea, at least for SUNION and SDIFF. The set we're creating is temporary.
> 
> But sunionDiffGenericCommand is also used for SUNIONSTORE and SDIFFSTORE (called with `dstkey != NULL`). For the STORE commands, the object is not temporary. It is stored in a key afterwards. In this case, we may want to store a compact representation, so here I agree with @hpatro's comment.
> 
> > I thought the decision of choosing `intset` as the default encoding type for the interim operation was made to have a very low memory footprint and move to `listpack`/`ht` if required.
> 
> I can see three options:
> 
> 1. Initialize as HT only if dstset == NULL and intset otherwise
> 2. Initialize as HT but for the store commands (dst != NULL) try to convert to listpack or intset afterwards. Currently, we only convert to "larger" encodings, i.e. we never convert from HT to listpack, for example.
> 3. Just accept that SUNIONSTORE and SINTERSTORE always stores HT encoded sets (current PR implementation).
> 
> At the minimum, we can do 1. I don't know if 2 is complex or if 3 is risky about using too much memory. WDYT?

@zuiderkwast Thanks for the suggestions.

Actually I am ok with both 1 and 3, for the 3, maybe I can help to measure the memory size gap between listpack and hashtable in future, to understand if the memory gap was acceptable compared with performance boost.

For this patch, to keep simple, I take the option 1 :).

**Comment by zuiderkwast** [comment]
> Actually I am ok with both 1 and 3, for the 3, maybe I can help to measure the memory size gap between listpack and hashtable in future, to understand if the memory gap was acceptable compared with performance boost.

I'm not very worried about the memory consumption, but it is surprising if you create a set using SADD, it will use less memory and if you create the same set using SUNIONSTORE it uses more memory. Predictable behaviour is good.

> For this patch, to keep simple, I take the option 1 :).

Sounds good.

**Review by zuiderkwast — APPROVED** [review]

**Pull request merged**
