### PR TITLE
Update for latest typos

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
@zuiderkwast this ignores most of the latest batch.  Many of these could be updated in the source to use more clear names that would avoid the extra whitelisting, but I've only fixed the clear spelling mistakes.

**Review by zuiderkwast — APPROVED** [review]
Awesome

**Comment by zuiderkwast** [comment]
Can we pin it to a specific version, so things don't start to break whenever there is a new version?

**Comment by jayvdb** [comment]
Yes, you can change https://github.com/valkey-io/valkey/blob/unstable/.github/workflows/spell-check.yml#L22 to be a specific version of the action, like https://github.com/taiki-e/install-action/releases/tag/v2.32.2 , and it will be more stable

**Pull request merged**
