### PR TITLE
Cherrypick bug fixes into 7.2 branch

### LINKED ISSUE #561: Integrate the bugfixes of Redis 7.2.5
Redis 7.2.5 has been published: https://github.com/redis/redis/releases/tag/7.2.5

This release uses the "old" Redis license.

Please integrate the bugfixes of this release into Valkey.

### PR DESCRIPTION
**Pull request by murphyjacob4**
Includes commits:

- https://github.com/valkey-io/valkey/commit/b3aaa0a1362d229ba1ecd44629655f76c77304ec
- https://github.com/valkey-io/valkey/commit/1f00c951c27f0332fd8e703beaf9e28cb404a0b4
- https://github.com/valkey-io/valkey/commit/492021db95288be2095ec7f1db2ee043fac3c2d9
- https://github.com/valkey-io/valkey/commit/5fdaa53d20c82c99042e79b737fb9bc157a73d60
- https://github.com/valkey-io/valkey/commit/763827c98144fa83b4fc50eb4cae7ec4d63e7925
- https://github.com/valkey-io/valkey/commit/da727ad445a640950baa097124070468a0316cc9

Fixes #561

### CODE REVIEW

**Comment by murphyjacob4** [comment]
Added https://github.com/valkey-io/valkey/commit/45a35a79c761766d46b3d97169cf62969e2c9ff4 to fix the test failure

**Comment by enjoy-binbin** [comment]
What judgment is used to select these commits? I see we are missing some commits, please check https://github.com/redis/redis/pull/13272/commits

**Comment by madolson** [comment]
Yeah, it looks like there are a bunch of other fixes that fix some issues with the ones we included. I didn't see any commit we shouldn't cherry-pick from the list that binbin sent.

**Comment by murphyjacob4** [comment]
Sounds good - I had gotten the previous list from https://github.com/valkey-io/valkey/issues/561#issuecomment-2136676042.

Added the other commits from the provided list

Note that https://github.com/valkey-io/valkey/commit/c67f39142ca8fe4d544835156403e0c0cf51a0f5 is already in 7.2, so not cherry-picking that one

**Review by enjoy-binbin — APPROVED** [review]
Ths commits LGTM. i guess we need to update REDIS_VERSION? (we can do this in the next release)
```
/* Redis OSS compatibility version, should never
 * exceed 7.2.x. */
#define REDIS_VERSION "7.2.4"
#define REDIS_VERSION_NUM 0x00070204
```

**Comment by murphyjacob4** [comment]
Yeah it probably makes sense to bump both Redis and Valkey versions. I think we can follow up this PR with another PR similar to https://github.com/valkey-io/valkey/pull/305 to include release notes and the versioning info. Or I can just do it in this PR. What do you think?

**Comment by enjoy-binbin** [comment]
lets do it it in another PR (the release one, with the release notes), i think @madolson will handle it after we make a decision about the new release

**Comment by PingXie** [comment]
There seems to be some test failures but we have been seeing them in other test passes as well. I am suspecting they are related to https://github.com/valkey-io/valkey/issues/609. Let's merge now and address #609 separately and we can add the fix to the next 7.2 patch release as well.

**Comment by enjoy-binbin** [comment]
@PingXie what kind of merge you are using when you merge this PR? this look like a squash merge? the commit sitting in 7.2 branch looks odd.

**Comment by PingXie** [comment]
Yes it is a squash merge. Do we want to keep the original commit history?

**Comment by enjoy-binbin** [comment]
yes, i want to keep the original commit history.

also if the commit (in this PR/branch) has something like `(cherry picked from commit xxx)` that can link to the very beginning commit that will be great. like doing git cherry-pick -x

**Comment by PingXie** [comment]
I see. I don't have a strong preference either way (squash or not). Do you prefer to revert and redo the cherry picks or can we keep this one? Looks like we can still easily get to the original commits from the commit message.

**Comment by enjoy-binbin** [comment]
I suggest doing a git reset --hard (since it is new and we don't actually release the code in release branch), then redo the cherry-pick things (with -x option) and do a rebase-merge or do a plain-merge (or just push these commits to the branch), but i am not sure, lets seeks some suggestions @valkey-io/core-team 

> Looks like we can still easily get to the original commits from the commit message.

actually the top comment are missing some other original commits.

**Comment by zuiderkwast** [comment]
Yes, I agree with @enjoy-binbin that it's good to keep each commit. We can enable rebase-merge in the admin config temporarily when want to merge something like this and then we can disable it again afterwards.

**Comment by PingXie** [comment]
I am aligned on keeping all commits when preparing future patches (and we don't need to mess with the admin configs since only the core team has the permission to merge). 

The question here though is whether we should redo *this* merge? I am inclined to keep it. Vote?

**Comment by enjoy-binbin** [comment]
I voted to redo the merge. The squashed merge is a bit ugly, and it is not easy to track, and it is also hard to do the cherry-pick when other forks merge this version (a large commit merges many small ones, which may cause conflicts)

**Comment by enjoy-binbin** [comment]
we discussed it in a meeting and we want to redo the merge (the code is not release yet so we have the chance). it is also quite simple.

1. Ping do a git reset --hard in the 7.2 branch
2. murphyjacob4 re-open the PR base on the branch (the local branch is still retain in his repo)
3. Ping do a rebase-merge (after we double check the commits has the same commit id)

**Pull request merged**
