### PR TITLE
Rename redis.tcl to valkey.tcl

### PR DESCRIPTION
**Pull request by hwware**
Test passed.

### CODE REVIEW

**Review by zuiderkwast — CHANGES_REQUESTED** [review]
valkey.tcl defines a lot of functions and structures called `redis`. This is just confusing. If we rename the client lib, rename the functions and types to valkey too, or otherwise just leave it with the name redis.

**Comment by hwware** [comment]
> valkey.tcl defines a lot of functions and structures called `redis`. This is just confusing. If we rename the client lib, rename the functions and types to valkey too, or otherwise just leave it with the name redis.

In this file, a lot of proc and global variables are defined by redis* name. In fact, we can rename all of them to valkey*, do you think this is a branding name issue or just leave them as a redis legacy?

**Comment by zuiderkwast** [comment]
Yes, I think it's a good idea to rename all redis to valkey in the tests. It is safe and the code will still work. Just don't change redis in copyright and license text in the files.

I don't think there is a trademark issue at all in the tests. We can keep "redis" if we want. The only reason to change it is that it is nice to remove it. Do you think it's better to just keep "redis" everywhere in the tests?

**Comment by enjoy-binbin** [comment]
i have seen some PRs doing this rename things (like #287). since now that we have started, let's rename them all in tcl tests.

personally, i want to do this in a big PR so that we don't have a lot of commits. Changing it is very simple, it only needs to pass CI and does not require much review. But i am ok with spitting it into multiple small PRs.

**Comment by zuiderkwast** [comment]
I like @enjoy-binbin's suggestion of one big PR for all TCL tests. If we change exactly everywhere, theoretically everything should work.

    "Redis" -> "Valkey"
    "redis" -> "valkey"
    "REDIS" -> "VALKEY"

**Comment by zuiderkwast** [comment]
This is part of #155 but i see no link between issue and pr.

**Comment by zuiderkwast** [comment]
This PR is outdated now after #287 was merged.

#287 changed everything inside the test files, but it didn't rename the file redis.tcl to valkey.tcl. We still need to do that.

The changes in tests/README.md are also good.

@hwware do you want to update this PR?

**Comment by hwware** [comment]
> This PR is outdated now after #287 was merged.
> 
> #287 changed everything inside the test files, but it didn't rename the file redis.tcl to valkey.tcl. We still need to do that.
> 
> The changes in tests/README.md are also good.
> 
> @hwware do you want to update this PR?

  let me refresh it. Thanks

**Comment by hwware** [comment]
> This PR is outdated now after #287 was merged.
> 
> #287 changed everything inside the test files, but it didn't rename the file redis.tcl to valkey.tcl. We still need to do that.
> 
> The changes in tests/README.md are also good.
> 
> @hwware do you want to update this PR?

Rebase done, and pass all tests, pls take a look, Thanks

**Review by zuiderkwast — APPROVED** [review]
Great!

**Pull request merged**
