### PR TITLE
upgrade centos7 to centos stream9

### LINKED ISSUE #527: Replace CentOS 7 image with CentOS Stream 9
CentOS 7 is EoL, we should replace it with the replacement which is CentOS Stream. CentOS Stream is about to be EoL https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/. The official container image is being distributed from [quay.io/centos/centos:stream9](http://quay.io/centos/centos:stream9).

We should consider adding AlmaLinux 8, which has a longer support history. https://endoflife.date/almalinux We can use the container from https://hub.docker.com/_/almalinux.

Should update https://github.com/valkey-io/valkey/blob/005a018db687568219e33f1119b034f653133869/.github/workflows/daily.yml#L675 as well as the other three centos targets.

### PR DESCRIPTION
**Pull request by adetunjii**
- Add support for Almalinux

Closes #527

### CODE REVIEW

**Review by madolson — COMMENTED** [review]
I see you formatted the YAML files. If we go down that path, I would like to add some automated format checker as part of the build so they don't become "unformatted" again. My preference would be we split this into two PRs, do the CentOS updates first (to unblock your other PR) and then add the formatter (you're more than welcome to pick that up if you want).

**Comment by adetunjii** [comment]
> I see you formatted the YAML files. If we go down that path, I would like to add some automated format checker as part of the build so they don't become "unformatted" again. My preference would be we split this into two PRs, do the CentOS updates first (to unblock your other PR) and then add the formatter (you're more than welcome to pick that up if you want).

@madolson Yh sure. Not a problem. Please just create an issue for it. I'll pick it up

**Comment by madolson** [comment]
@adetunjii  https://github.com/valkey-io/valkey/issues/533

**Comment by zuiderkwast** [comment]
Replaced by #543. Thanks anyway!

**Pull request closed without merging**
