### PR TITLE
Restore comments for client flags

### PR DESCRIPTION
**Pull request by PingXie**

### CODE REVIEW

**Review by zuiderkwast — COMMENTED** [review]
Great, but what happened to clang-format? It freaked out?

**Comment by PingXie** [comment]
> Great, but what happened to clang-format? It freaked out?

Yeah. I was trying to disable the trailing comment alignment check. I thought it was an easy one but like any other small changes it became a surprise. I have reverted the .clang-format change. This should be good now. Will try fixing the trailing comment alignment some other day.

**Review by hpatro — COMMENTED** [review]
All of these must be copy-paste. But I think we should decide if we should have period at the end of comment or not? :D

**Comment by PingXie** [comment]
> But I think we should decide if we should have period at the end of comment or not? 

Right it is an eye sore for me too :p

**Review by zuiderkwast — APPROVED** [review]
> we should decide if we should have period at the end of comment or not

If there are multiple sentences in one comment, then they need periods to be readable. Otherwise I don't care.

**Comment by madolson** [comment]
> If there are multiple sentences in one comment, then they need periods to be readable. Otherwise I don't care.

I omit periods if the comment is a sentence fragment and not a full sentence, but also don't really care.

**Pull request merged**
