### PR TITLE
Prevent clang-format in certain places

### PR DESCRIPTION
**Pull request by zuiderkwast**
This is a preparation for adding clang-format.

These comments prevent automatic formatting in some places. With these exceptions, we will be able to run clang-format on the rest of the code.

This is a preparation for #323.

### CODE REVIEW

**Review by enjoy-binbin — APPROVED** [review]

**Review by PingXie — APPROVED** [review]

**Comment by hwware** [comment]
Before merging this PR, can we just clarify under which condition, developer should /* clang-format off */ flag? 
I think we should describe this in some places so that all people can follow this rule.

**Comment by zuiderkwast** [comment]
> Before merging this PR, can we just clarify under which condition, developer should /* clang-format off */ flag? I think we should describe this in some places so that all people can follow this rule.

We can describe all coding rules. Now we don't have any written rules. But I don't think it should be a blocker. This (clang-format off) will probably be very rare for new code. We can do it for each PR, if it ever comes up.

**Comment by PingXie** [comment]
The whole point of applying clang-format is to get consistency in our code base without every committer having to read through a long documentation and reviewers spending their brain cycles in nitpicking styling issues :-).

**Comment by zuiderkwast** [comment]
Right, so we can say something in CONTRIBUTING.md that we use clang-format. Disabling it should normally not be done but we can accept it in cases similar to the ones in this PR. Is that OK or do you have another idea?

**Comment by zuiderkwast** [comment]
Btw, coding style can also include naming, camel/snake case and more, not covered by clang-format.

**Comment by hwware** [comment]
I would like to add one tag for this pr for documentation later. No other opinion so far.
We could merge it.

**Review by hwware — APPROVED** [review]

**Comment by madolson** [comment]
> I would like to add one tag for this pr for documentation later. No other opinion so far.

What documentation do we need to add?

**Comment by madolson** [comment]
(The PR looked fine to me)

**Comment by zuiderkwast** [comment]
> > I would like to add one tag for this pr for documentation later. No other opinion so far.
> 
> What documentation do we need to add?

We can describe when it's OK vs not OK to use `/* clang-format off */`. This probably belongs in CONTRIBUTING.md or similar. Not in the doc repo.

> (The PR looked fine to me)

Sorry I was eager to merge it. :)

**Pull request merged**
