### PR TITLE
Rename redis.info to valkey.info in LCOV

### PR DESCRIPTION
**Pull request by vitahlin**
Change the name of lcov test as follows: 
image

### CODE REVIEW

**Review by hwware — APPROVED** [review]

**Comment by hwware** [comment]
LGTM

**Comment by madolson** [comment]
We should automate running with coverage too so they're attached to PR :)

**Comment by vitahlin** [comment]
> We should automate running with coverage too so they're attached to PR :)

We can also display the coverage results in the README.md.

Do you think it's better to open a new PR or deal with it in the current one? @madolson

**Review by zuiderkwast — APPROVED** [review]
Good!

Automatic cover report is a future issue. It seems like more work.

**Comment by vitahlin** [comment]
I personally believe in keeping commits as focused and concise as possible. I'll address the issue of test coverage in a new pull request to ensure its independence and clarity. Thanks for your understanding.

**Pull request merged**
