### PR TITLE
Rename redisContext to serverContext

### PR DESCRIPTION
**Pull request by 9bany**
A part of: https://github.com/valkey-io/valkey/issues/144

### CODE REVIEW

**Comment by 9bany** [comment]
These changes are big enough to review @zuiderkwast

**Review by zuiderkwast — CHANGES_REQUESTED** [review]
I believe this struct is defined in hiredis, which is a vendored dependency.

Until we have forked hiredis and renamed these structs in the fork, I think we shall keep the vendored dependency as it is, so we don't diverge from the upstream.

The usage in redis-cli, redis-benchmark, etc. all use hiredis as a client library, so they use this vendored hiredis.

So to sum up: I don't think we shall merge this. Thanks anyway!

**Comment by 9bany** [comment]
Clear !  thanks @zuiderkwast

**Comment by zuiderkwast** [comment]
Great. I hope you didn't spend too much time? Global search/replace right?

**Pull request closed without merging**
