### PR TITLE
Remove centos7 test jobs in 7.2 branch

### PR DESCRIPTION
**Pull request by PingXie**
Backport #543

### CODE REVIEW

**Review by enjoy-binbin — APPROVED** [review]

**Comment by PingXie** [comment]
hmm all new OS flavors failed. Is it worth bringing them downlevel or we should just remove centos7?

**Comment by enjoy-binbin** [comment]
i see the daily CI can pass, why did this fail? If it is took too much times, i think we can skip (ignore) it for now?

**Comment by madolson** [comment]
They seem to be failing because we didn't backport https://github.com/valkey-io/valkey/pull/595 ? Let me submit a PR for that. EDIT: https://github.com/valkey-io/valkey/pull/772

**Comment by PingXie** [comment]
> They seem to be failing because we didn't backport #595 ? Let me submit a PR for that. EDIT: #772

#772 is a good fix :-).

The freebsd ones seem to be known issues. Are the two fedora tests a concern? They seem to have hung.

**Comment by madolson** [comment]
There was another fix that was causing hanging cluster tests we investigated a few weeks ago. Let me see if I can find it.

**Comment by madolson** [comment]
I believe the one I was thinking of was https://github.com/valkey-io/valkey/pull/717, but that doesn't seem related. I think we should just merge this one.

**Review by madolson — APPROVED** [review]

**Comment by madolson** [comment]
For the BSD tests, it seems like we (Yossi) scoped them down significantly on unstable awhile ago. See, https://github.com/valkey-io/valkey/commit/a9e73c00bc1056eae4db98ca4bd1c126d994889d. Maybe we should do that as well if they aren't working?

**Comment by PingXie** [comment]
> For the BSD tests, it seems like we (Yossi) scoped them down significantly on unstable awhile ago. See, [a9e73c0](https://github.com/valkey-io/valkey/commit/a9e73c00bc1056eae4db98ca4bd1c126d994889d). Maybe we should do that as well if they aren't working?

SG - I will do it later today.

**Pull request merged**
