### PR TITLE
Backport fixes to Valkey 7.2.6

### PR DESCRIPTION
**Pull request by PingXie**

### CODE REVIEW

**Comment by enjoy-binbin** [comment]
i guess we also need to backport #442, a lot of new tests rely on it.

**Comment by PingXie** [comment]
> i guess we also need to backport #442, a lot of new tests rely on it.

That is a big one. I think I found the missing test helper function. This should work now.

**Comment by zuiderkwast** [comment]
Write release notes too?

**Comment by madolson** [comment]
> Write release notes too?

Maybe we have a dedicated PR for the release notes? Seems weird to couple that with partial set of fixes.

**Review by zuiderkwast — APPROVED** [review]
CentOS 7 is gone so we'll obviously need to remove that job from the 7.2 branch too.

**Pull request merged**
