### PR TITLE
Update comment in cluster_legacy.h

### PR DESCRIPTION
**Pull request by bentotten**
Update comment suggesting clusterMsgPingExtTypes to clusterMsgPingtypes as clusterMsgPingExtTypes does not exist

### CODE REVIEW

**Review by enjoy-binbin — APPROVED** [review]
please sign this: https://github.com/valkey-io/valkey/blob/unstable/CONTRIBUTING.md#developer-certificate-of-origin

**Comment by bentotten** [comment]
> please sign this: https://github.com/valkey-io/valkey/blob/unstable/CONTRIBUTING.md#developer-certificate-of-origin

Neat! I believe I signed it correctly now, but am unsure how to rerun the test - is this something you do or do I need to create a new PR?

**Comment by enjoy-binbin** [comment]
you can see the detail git commit message in your commit, it did not signoff. you can take a look in the unstable branch commit, all commits have a `Signed-off-by: xxxx`

**Comment by madolson** [comment]
@bentotten The easier thing you can do while on the patch-2 branch is:
```
commit -s --amend
git push origin patch-2 --force
```

If you have git setup to add your name. That will add the signoff.

**Comment by bentotten** [comment]
Complete (I think) 

Note: additional comment improvement for `uint16_t ver;` while we're here

**Review by madolson — APPROVED** [review]

**Pull request merged**
