### PR TITLE
Replacing REDIS_STATIC with static

### PR DESCRIPTION
**Pull request by ouriamzn**
As discussed, we want to remove the old `REDIS_STATIC` flag which is no longer relevant.

When moving from Redis to Valkey we renamed all REDIS flags in Makefile.
The REDIS_STATIC flag was renamed to SERVER_STATIC, but this change was not updated in some of the files.

After discussing it with @madolson and @ranshid, we decided that since this was introduced 10 years ago, and in many places in the code base we simply use `static`, we should simplify and remove the flag entirely.

### CODE REVIEW

**Comment by bbarani** [comment]
@ouriamzn can you please fix the DCO? It looks like the commit is incorrectly signed off.

**Comment by zuiderkwast** [comment]
> As discussed

That's nothing I've heard about. Who discussed this, when and where?

**Comment by madolson** [comment]
@zuiderkwast Previous PR: https://github.com/valkey-io/valkey/pull/684

**Review by ranshid — APPROVED** [review]
Thank you. LGTM

I think fix the top comment so that this PR stand by itself.

**Review by zuiderkwast — APPROVED** [review]

**Review by madolson — APPROVED** [review]

**Pull request merged**
