### PR TITLE
Very minor misspelling in some tests

### PR DESCRIPTION
**Pull request by iandouglas**
Fix misspelling "faiover" instead of "failover" in two test cases.

### CODE REVIEW

**Comment by hwware** [comment]
the updated typo only for the test case name, should not be reason cause test cases failure

BTW. DCO pls sign off.

**Comment by iandouglas** [comment]
My apologies; I wasn't implying that the misspellings caused the tests to fail; I simply noticed the misspellings because these tests had failed during a build.

**Comment by madolson** [comment]
> My apologies; I wasn't implying that the misspellings caused the tests to fail; I simply noticed the misspellings because these tests had failed during a build.

No worries. As wen mentioned though, we require a DCO to submit code. You can read more about it here: https://github.com/valkey-io/valkey/blob/unstable/CONTRIBUTING.md#developer-certificate-of-origin. You can see one of the checks failing. You'll need to sign it and git force push over your change.

**Review by zuiderkwast — APPROVED** [review]
LGTM

Please fix the DCO. If you click on Details near the failed CI job :x: DCO, you can find some help how to fix it.

**Comment by iandouglas** [comment]
fixed

**Pull request merged**
