### PR TITLE
New logo "hexagon labyrinth"

### PR DESCRIPTION
**Pull request by zuiderkwast**
ASCII version of the logo posted by @dizys here: https://github.com/valkey-io/valkey-website/issues/7#issuecomment-2033284794

image

### CODE REVIEW

**Comment by PingXie** [comment]
Can you please post the real printout? It is easier to see the effect that way

**Comment by zuiderkwast** [comment]
Done.

The width is exactly the same as the Redis logo, to avoid wrapping in narrow terminals.

**Comment by PingXie** [comment]
> Done.
> 
> 
> 
> The width is exactly the same as the Redis logo, to avoid wrapping in narrow terminals.

Thanks! Logo looks good to me. Looks like the url link was shifted right. Is it intended?

**Comment by zuiderkwast** [comment]
> Thanks! Logo looks good to me. Looks like the url link was shifted right. Is it intended?

It is shifted one space from the left, if that's what you mean. It's what the Redis logo did too.

**Comment by PingXie** [comment]
It is more than just a space?

8zqAsMcVVQZmV9E

**Comment by PingXie** [comment]
never mind. Redis has the same indentation. 
Screenshot 2024-04-06 11 16 04

**Review by PingXie — APPROVED** [review]
LGTM

**Comment by madolson** [comment]
```
"                .+@+.                                                \n"
"            .+@@@@@@@@@+.                                            \n"
"        .+@@@@@@@@+@@@@@@@@+.           Valkey %s (%s/%d) %s bit\n"
"    .+@@@@@@@@+'     '+@@@@@@@@+.                                    \n"
" .@@@@@@@@+'     .+.     '+@@@@@@@@.                                 \n"
" |@@@@+'     .+@@@@@@@+.     '+@@@@|
" |@@@|   .+@@@@@@@@@@@@@@@+.   |@@@|    Running in %s mode\n"
" |@@@|   |@@@@@*'' ''*@@@@@|   |@@@|    Port: %d\n"
" |@@@|   |@@@@'  .*.  '@@@@|   |@@@|    PID: %ld\n"
" |@@@|   |@@@(  (@@@)  )@@@|   |@@@|                                 \n"
" |@@@|   |@@@@.  '*'  .@@@@|   |@@@|                                 \n"
" |@@@|   |@@@@@*.   .*@@@@@|   |@@@|          https://valkey.io      \n"
" |@@@|   '+@@@@@@   @@@@@@+'   |@@@|                                 \n"
" |@@@@+.     |@@@   @@+'     .+@@@@|                                 \n"
" '@@@@@@@+   |@@@        .+@@@@@@@@'                                 \n"
"    '+@@@|   |@@@    .+@@@@@@@@+'                                    \n"
"        '|   |@@@@+@@@@@@@@+'                                        \n"
"             '+@@@@@@@@+'                                            \n"
"                '+@+'                                                \n"
```

I'm not sure this is much better, but this is what I came up with. The points that were bothering me with the proposal:
1. It's missing the keyhole.
2. It feels like its' angeled, whereas the logo we're proposing is a perfect hexagon (the bestagon)

The things I don't like about this:
1. ~~It feels crooked.~~ An earlier version was crooked, I think this is straight

Btw, it's also two characters taller.

**Comment by madolson** [comment]
```
"                .+#+.                                                \n"
"            .+#########+.                                            \n"
"        .+########+########+.           Valkey %s (%s/%d) %s bit\n"
"    .+########+'     '+########+.                                    \n"
" .########+'     .+.     '+########.                                 \n"
" |####+'     .+#######+.     '+####|
" |###|   .+###############+.   |###|    Running in %s mode\n"
" |###|   |#####*'' ''*#####|   |###|    Port: %d\n"
" |###|   |####'  .*.  '####|   |###|    PID: %ld\n"
" |###|   |###(  (@@@)  )###|   |###|                                 \n"
" |###|   |####.  '*'  .####|   |###|                                 \n"
" |###|   |#####*.   .*#####|   |###|          https://valkey.io      \n"
" |###|   '+######   ######+'   |###|                                 \n"
" |####+.     +###   ##+.     .+####|                                 \n"
" '#######+   |###        .+########'                                 \n"
"    '+###|   |###    .+########+'                                    \n"
"        '|   |####+########+'                                        \n"
"             '+########+'                                            \n"
"                '+#+'                                                \n"
```
Also sort of feeling # sign vibes.

**Comment by zuiderkwast** [comment]
@madolson your version is fine by me. My version lacks the dot in the middle. (I picked @ because it seemed more black than #, and I thought the b,d,q,p were funny as diagonals. This doesn't matter though.)

I can update this PR.

**Comment by madolson** [comment]
>  (I picked @ because it seemed more black than #, and I thought the b,d,q,p were funny as diagonals. This doesn't matter though.)

I'm fine with @ to be darker, I thought the angled lines was more "stylized", but I don't have a strong preference.

**Comment by madolson** [comment]
I posted my attempt here: https://github.com/valkey-io/valkey/pull/251

**Pull request closed without merging**
